"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
const values={"radius-max":"12","probe-radius":"1","plot-quantity":"xi","mass-input":"1","mass-unit":"solar","calc-radius":"1"};
const checked={"show-limits":true,"log-axis":false};
const methods=["setTransform","clearRect","save","restore","beginPath","arc","stroke","fill","moveTo","lineTo","fillRect","strokeRect","setLineDash","translate","rotate","fillText"];
const ctx=Object.fromEntries(methods.map(x=>[x,()=>{}]));ctx.measureText=t=>({width:String(t).length*7});
const map=new Map(),element=id=>{if(map.has(id))return map.get(id);const e={id,value:values[id]??"",checked:checked[id]??false,textContent:"",addEventListener:()=>{},replaceChildren(n){this.textContent=n.textContent;}};if(id==="metric-chart"){e.getBoundingClientRect=()=>({width:800,height:470,left:0});e.getContext=()=>ctx;}map.set(id,e);return e;};
let ready;
const sandbox={console,Math,Number,document:{documentElement:{dataset:{}},getElementById:element,createTextNode:t=>({textContent:String(t)}),addEventListener:(n,cb)=>{if(n==="DOMContentLoaded")ready=cb;}},getComputedStyle:()=>({getPropertyValue:n=>n==="--surface"?"#fff":""}),devicePixelRatio:1,addEventListener:()=>{},CustomEvent:function(){}};
sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync("assets/js/physics.js","utf8"),sandbox);ready();
assert.equal(element("radius-max-value").textContent,"12");
assert.ok(Number(element("xi-value").textContent.replaceAll(",",""))>.8);
assert.ok(Number(element("d-value").textContent.replaceAll(",",""))>.55);
assert.match(element("rs-output").textContent,/m$/);
assert.equal(typeof sandbox.SSZ.xi,"function");
console.log("OK: native metric explorer and calculators initialise without Chart.js");
